web:
  build: .
  ports:
   - "5000:5000"
  links:
   - aerospike
  hostname: dev.myapp.com
  environment:
    - AEROSPIKE_HOST=dev_aerospike_1   
aerospike:
  image: aerospike/aerospike-server:latest
  volumes: 
    - $PWD:/etc/aerospike
